[project]
name = "test"
version = "0.1.0"
description = ""
authors = [{ name = "hemengyang", email = "hmy0119@gmail.com" }]
dependencies = [
    "nonebot-adapter-console @ git+https://github.com/nonebot/adapter-console.git",
]
requires-python = ">=3.11"
license = { text = "MIT" }
